### ISSUE TITLE
Unable to download JS bundle

### ISSUE THREAD

**Issue by avishayil** [iodine/react-native-drawer-layout#32] opened 2015-12-28 09:40 UTC
Hi,

I can't seem to download JS bundle when requiring this package.
I thought in the beginning something is wrong with my setup, but them I tried to require it on another project and it seems that the packager is stuck always at 99% when downloading the bundle.

Any solutions?

**Comment by arshsingh** [comment] 2016-01-06 04:18
It's probably a babel transformation error. This should be fixed with https://github.com/iodine/react-native-drawer-layout/commit/761d899fc80187d2cf8cb08a633d9beb2f0a6c68

**Comment by browniefed** [comment] 2016-01-12 22:02
Would be great to get this published with the babel fix

**Comment by DanielMSchmidt** [comment] 2016-01-14 08:44
@avishayil Can you test if the bug still occurs in the latest version?

**Comment by DanielMSchmidt** [comment] 2016-01-16 09:26
May this be a duplicate of #37 ?

**Comment by browniefed** [comment] 2016-01-16 09:27
The reason is the current published version still includes whitelist in package.json causing Babel 6 issues

**Comment by DanielMSchmidt** [comment] 2016-01-16 09:36
No, 0.3.4 has no whitelist option in the package.json, it is the same one as currently on the master brach.

**Comment by browniefed** [comment] 2016-01-16 09:46
Ah good, I'll check in the morning, .3.4 wasn't published when I was testing

**Comment by DanielMSchmidt** [comment] 2016-01-18 10:24
@browniefed Hey, do you have feedback for me? I would love to get rid of the last bug issue :+1:

**Comment by browniefed** [comment] 2016-01-18 17:19
Everything looks good, thanks!

**Comment by DanielMSchmidt** [comment] 2016-01-18 20:21
Awesome!

**Closed as completed by DanielMSchmidt** 2016-01-18 20:21 UTC
Labels: bug
