### ISSUE TITLE
TouchableHighlight can not use

### ISSUE THREAD

**Issue by zjgnlzq** [iodine/react-native-drawer-layout#43] opened 2016-01-15 18:34 UTC
when i see with inspector, i find my TouchableHighlight element have be modified to TouchableWithoutFeedback

**Comment by DanielMSchmidt** [comment] 2016-01-15 22:05
Hi,

I am not quite sure how I may reproduce this issue, may you help me by describing exactly how I may achieve the same error in my code? 
I am not 100% sure what the problem is, but I may guess that you have a TouchableHighlight in the area which is not overlapped by the drawer-layout and you inspected it and the inspector shows a TouchableWithoutFeedback? In this case, this is intended, as we need a TouchableWithoutFeedback element to determine if there was a touch outside of the drawer layout and it may be closed.

**Comment by zjgnlzq** [comment] 2016-01-16 15:01
I found this problem in 0.3.4
@DanielMSchmidt  you can run DrawerLayoutExample in your code, then you can not click the "Open drawer" button

``` javascript
          <TouchableHighlight onPress={() => this.drawer.openDrawer()}>
            <Text>Open drawer</Text>
          </TouchableHighlight>

```

**Comment by DanielMSchmidt** [comment] 2016-01-17 09:18
Okay, now I understand. This is a duplicate of #15, so I will close this issue and you may watch the other one for info on that topic.

**Closed as completed by DanielMSchmidt** 2016-01-17 09:18 UTC
